=== samueleresca/nvd-api/nvd-models/schema/cve_change_history/cve_history_api_schema_2.0.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
    "title": "JSON Schema for NVD CVE History API version 2.0",
	"$id": "https://csrc.nist.gov/schema/nvd/api/2.0/history_api_json_2.0.schema",
    "definitions": {
		"defChange": {
			"properties": {
				"change": {"$ref": "#/definitions/changeItem"}
			},
			"required": ["change"],
			"additionalProperties": false
		},
		
		"changeItem": {
			"properties": {
				"cveId": {
					"type": "string",
					"pattern": "^CVE-[0-9]{4}-[0-9]{4,}$"
				},
				"eventName": {"type": "string"},
				"cveChangeId": {"type": "string", "format": "uuid"},
				"sourceIdentifier": {"type": "string"},
				"created": {"type": "string", "format": "date-time"},
				"details": {
					"type": "array",
					"items": {"$ref": "#/definitions/detail"}
				}
			},
			"required": ["cveId", "eventName", "cveChangeId", "sourceIdentifier"],
			"additionalProperties": false
        },
		
		"detail": {
			"properties": {
				"action": {"type": "string"},
				"type": {"type": "string"},
				"oldValue": {"type": "string"},
				"newValue": {"type": "string"}
			},
			"required": ["type"],
			"additionalProperties": false
		}
	},
		
    "type": "object",
    "properties": {
		"resultsPerPage": {"type": "integer"},
		"startIndex": {"type": "integer"},
		"totalResults": {"type": "integer"},
		"format": {"type": "string"},
		"version": {"type": "string"},
		"timestamp": {"type": "string", "format": "date-time"},
        "cveChanges": {
            "description": "Array of CVE Changes",
            "type": "array",
            "items": {"$ref": "#/definitions/defChange"}
        }
    },
    "required": [
		"resultsPerPage",
		"startIndex",
		"totalResults",
		"format",
		"version",
		"timestamp"
    ]
}

=== samueleresca/nvd-api/src/test_data/cve_change_history.json
{"resultsPerPage":1,"startIndex":0,"totalResults":1,"format":"NVD_CVEHistory","version":"2.0","timestamp":"2023-02-24T22:39:32.583","cveChanges":[{"change":{"cveId":"CVE-2022-3115","eventName":"Initial Analysis","cveChangeId":"1A6CC8F6-5DB2-40AA-99C7-71710FE37293","sourceIdentifier":"nvd@nist.gov","created":"2022-12-16T21:24:16.357","details":[{"action":"Added","type":"CVSS V3.1","newValue":"NIST AV:L\/AC:L\/PR:L\/UI:N\/S:U\/C:N\/I:N\/A:H"},{"action":"Changed","type":"Reference Type","oldValue":"https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=2153058 No Types Assigned","newValue":"https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=2153058 Issue Tracking, Third Party Advisory"},{"action":"Changed","type":"Reference Type","oldValue":"https:\/\/git.kernel.org\/pub\/scm\/linux\/kernel\/git\/torvalds\/linux.git\/commit\/?h=v5.19-rc2&id=73c3ed7495c67b8fbdc31cf58e6ca8757df31a33 No Types Assigned","newValue":"https:\/\/git.kernel.org\/pub\/scm\/linux\/kernel\/git\/torvalds\/linux.git\/commit\/?h=v5.19-rc2&id=73c3ed7495c67b8fbdc31cf58e6ca8757df31a33 Patch, Vendor Advisory"},{"action":"Added","type":"CPE Configuration","newValue":"OR\n     *cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:* versions up to (excluding) 5.16.0\n     *cpe:2.3:o:linux:linux_kernel:5.16.0:-:*:*:*:*:*:*\n     *cpe:2.3:o:linux:linux_kernel:5.16.0:rc1:*:*:*:*:*:*\n     *cpe:2.3:o:linux:linux_kernel:5.16.0:rc2:*:*:*:*:*:*\n     *cpe:2.3:o:linux:linux_kernel:5.16.0:rc3:*:*:*:*:*:*\n     *cpe:2.3:o:linux:linux_kernel:5.16.0:rc4:*:*:*:*:*:*\n     *cpe:2.3:o:linux:linux_kernel:5.16.0:rc5:*:*:*:*:*:*\n     *cpe:2.3:o:linux:linux_kernel:5.16.0:rc6:*:*:*:*:*:*"}]}}]}
